USE ROLE ACCOUNTADMIN;

-- Create the `BI_USERS` role
CREATE ROLE IF NOT EXISTS BI_USERS;
GRANT ROLE BI_USERS TO ROLE ACCOUNTADMIN;

-- Create the default warehouse if necessary
CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE BI_USERS;

-- Create the `dbt` user and assign to role
CREATE USER IF NOT EXISTS bi_user
  PASSWORD='dbtPassword123'
  LOGIN_NAME='bi_user'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE='BI_USERS'
  DEFAULT_NAMESPACE='AIRBNB.DEV'
  COMMENT='BI user used for data BI_USERSation';
GRANT ROLE BI_USERS to USER bi_user;

-- Set up permissions to role `transform`
GRANT SELECT ON WAREHOUSE COMPUTE_WH TO ROLE transform; 
GRANT ALL ON DATABASE AIRBNB to ROLE transform;
GRANT ALL ON ALL SCHEMAS IN DATABASE AIRBNB to ROLE transform;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE AIRBNB to ROLE transform;
GRANT ALL ON ALL TABLES IN SCHEMA AIRBNB.RAW to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA AIRBNB.RAW to ROLE transform;